version: '2'
services:
  web:
    build: .
    image: emojitracker/rest-api
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=8000
      - RACK_ENV=development
      - MEMCACHIER_SERVERS=memcache
      - REDIS_URL=redis://redis:6379
    depends_on:
      - memcache
      - redis

  feeder:
    image: emojitracker/fakefeeder
    command: ["-target=redis://redis:6379", "-rate=250"]
    depends_on:
      - redis

  redis:
    image: redis

  memcache:
    image: memcached:alpine
